name: Inspect

on: push

defaults:
  run:
    shell: bash

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Deps
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Fetch Deps
      run: yarn install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Deps
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Lint
      run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Deps
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Test
      run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: fetch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Deps
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Build
      run: yarn build
    - name: Upload Builds
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          packages/*/lib/
          packages/*/types/
          packages/*/ts*/

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Deps
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Download Builds
      uses: actions/download-artifact@v2
      with:
        name: build
        path: packages
    - name: Build Docs
      run: yarn docs
    - name: Upload Docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: |
          packages/*/docs/

  gh-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' }}
    needs:
    - build
    - docs
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Deps
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles( 'yarn.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Download Builds
      uses: actions/download-artifact@v2
      with:
        name: build
        path: public/packages
    - name: Download Docs
      uses: actions/download-artifact@v2
      with:
        name: docs
        path: public/packages
    - name: Copy Examples
      run: |
        for d in packages/*; do
          if [[ -e "$d/examples" ]]; then
            mkdir -p public/$d
            cp -r $d/examples public/$d
          fi
        done
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
